version: '3'

tasks:
  default:
    cmds:
      - task --list
    silent: true

  up:
    desc: up frontend container
    cmds:
      - MODE=stage docker compose up --build -d

  down:
    desc: cancel frontend container
    cmds:
      - docker compose down

  dev:
    desc: up only frontend side of project and develope in real time
    cmds:
      - npm install
      - npm run dev

  lint:
    desc: formatting project
    cmds:
      - npx prettier . --write
