version: '3'

tasks:
  default:
    cmds:
      - task --list
    silent: true

  dev:
    desc: up only frontend side of project and develope in real time
    cmds:
      - npm install
      - npm run dev

  lint:
    desc: formatting project
    cmds:
      - npx prettier . --write
