name: Build Docker image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: write

env:
  IMAGE: ghcr.io/selfdevcomp/frontend

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          docker build -f infra/Dockerfile -t $IMAGE:${{ github.sha }} .

      - name: Login to GHCR
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push
        if: github.event_name == 'push'
        run: |
          docker push $IMAGE:${{ github.sha }}