name: Build

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [dev]

permissions:
  contents: read
  packages: write

env:
  IMAGE: ghcr.io/selfdevcomp/frontend

jobs:
#   lint:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4

#       - name: Check code
#         run: |
#           task lint

  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
            MODE=prod docker compose -f infra/docker-compose.yaml build

      - name: Login to GHCR
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push
        if: github.event_name == 'push'
        run: |
          docker push $IMAGE:${{ github.sha }}